name: Déployer une app Angular sur GitHub Pages

on:
  push:
    branches:
      - master  # ou main, selon ta branche par défaut
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installer les dépendances
        run: npm install

      - name: Construire l'application Angular dans /docs
        run: |
          npx ng build --output-path=docs --base-href="/app/"
          touch docs/.nojekyll

      - name: Commit et push vers master
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add docs
          git commit -m "Déploiement Angular vers GitHub Pages [automatique]" || echo "Rien à valider"
          git push

